version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: 